version: '3.8'

services:
  pm-jira-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=dev-secret-key-for-local-testing
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-service-execution-uat-bb7}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - GITBOOK_API_KEY=${GITBOOK_API_KEY}
    volumes:
      # Mount config directory for easy configuration management
      - ./config:/app/config
      # Mount logs directory for debugging
      - ./logs:/app/logs
      # Mount Google Cloud credentials if available
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:/app/credentials.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - pm-jira-agent

networks:
  pm-jira-agent:
    driver: bridge

# For production deployment with external database (future use)
# volumes:
#   pm_data:
#     driver: local