#!/bin/bash

# Setup Vertex AI Agent Builder for PM Jira Agent  
# Project: service-execution-uat-bb7
# Region: europe-west9

PROJECT_ID="service-execution-uat-bb7"
REGION="europe-west9"
AGENT_NAME="pm-jira-agent"

echo "🤖 Setting up Vertex AI Agent Builder (Updated 2025)..."
echo "Project: $PROJECT_ID"
echo "Region: $REGION"
echo "Agent: $AGENT_NAME"

# Set project
gcloud config set project $PROJECT_ID

echo ""
echo "📋 Current Vertex AI Agent Builder Options (2025):"
echo ""
echo "OPTION 1: Conversational Agent (Dialogflow-based)"
echo "1. Go to: https://console.cloud.google.com/vertex-ai/agents"
echo "2. Click 'CREATE A NEW APP'"
echo "3. Choose 'Conversational agent'"
echo "4. Configure:"
echo "   - Display Name: $AGENT_NAME"
echo "   - Location: global (or $REGION)"
echo "   - Choose 'Build your own'"
echo "5. Agent Configuration:"
echo "   - Playbook Name: PM Jira Ticket Creator"
echo "   - Agent Goal: Transform user requests into high-quality Jira tickets"
echo "   - Model: gemini-1.5-flash (or gemini-1.5-pro)"
echo ""
echo "OPTION 2: Agent Development Kit (ADK) - Recommended for Phase 2"
echo "1. Install Agent Development Kit:"
echo "   pip install google-cloud-vertex-ai"
echo "2. Create agent with tools (Python code)"
echo "3. Deploy to Vertex AI Agent Engine"
echo ""
echo "📋 RECOMMENDED APPROACH FOR PHASE 2:"
echo ""
echo "STEP 1: Start with Conversational Agent (Simple)"
echo "1. Navigate to: https://console.cloud.google.com/vertex-ai/agents"
echo "2. Enable required APIs if prompted"
echo "3. Click 'CREATE A NEW APP' → 'Conversational agent'"
echo "4. Agent Details:"
echo "   - Display Name: PM Jira Agent"
echo "   - Location: global"
echo "   - Build your own: Yes"
echo ""
echo "STEP 2: Configure Agent Instructions"
echo "Goal: 'Create comprehensive, high-quality Jira tickets from user requests'"
echo ""
echo "Instructions:"
echo "'You are a Product Manager assistant specializing in creating detailed Jira tickets."
echo "Your workflow:"
echo "1. Analyze user requests for technical feasibility"
echo "2. Research context from GitBook documentation"
echo "3. Create user stories with acceptance criteria"
echo "4. Ensure tickets meet Definition of Ready standards"
echo "5. Only create tickets with quality score ≥ 0.8'"
echo ""
echo "STEP 3: Add Tools (Phase 2 Development)"
echo "- Create custom tools for GitBook and Jira integrations"
echo "- Connect Cloud Functions as external APIs"
echo "- Implement quality scoring logic"
echo ""
echo "✅ Phase 1 Complete: API integrations working!"
echo "🔄 Phase 2: Choose your agent creation approach above"
echo ""
echo "📡 Your Cloud Function URLs:"
echo "GitBook API: https://gitbook-api-jlhinciqia-od.a.run.app"
echo "Jira API: https://jira-api-jlhinciqia-od.a.run.app"
echo ""
echo "📚 Documentation References:"
echo "- Agent Builder Overview: https://cloud.google.com/vertex-ai/generative-ai/docs/agent-builder/overview"
echo "- Agent Codelab: https://codelabs.developers.google.com/devsite/codelabs/building-ai-agents-vertexai"
echo "- Agent Engine Quickstart: https://cloud.google.com/vertex-ai/generative-ai/docs/agent-engine/quickstart"